# Also works for Swift
language: objective-c

# Xcode version
osx_image: xcode8.1sneakpeek

# Specify the opening file for the project
xcode_workspace: TouchDraw.xcworkspace

# Specify the main build
xcode_scheme: TouchDraw

# Specify the last iOS sdk
xcode_sdk: iphonesimulator

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination 'name=iPhone 6' build test | xcpretty
